// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           20
// Async Callback:                       1
// Total number of exported functions:  22

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    opendex_sc_sft_nft_staking
    (
        init => init
        getStakingSftCollectionId => staking_sft_collection_id
        getRewardToken => reward_token
        getStakedNftCollectionId => staked_nft_collection_id
        getRewardPerSecond => reward_per_second
        getTotalStaked => total_staked
        getFeeReceiver => fee_receiver
        getPerformanceFeePercent => performance_fee_percent
        getRewardPeriodEnd => reward_period_end
        getRewardStartTime => reward_start_time
        stake => stake
        unstake => unstake
        claimRewards => claim_rewards
        issueStakedNftCollection => issue_staked_nft_collection
        fundRewardsAndSetDuration => fund_rewards_and_set_duration
        setPerformanceFeePercent => set_performance_fee_percent
        setFeeReceiver => set_fee_receiver
        isAdmin => is_admin
        addAdmin => add_admin
        removeAdmin => remove_admin
        getAdmins => admins
    )
}

multiversx_sc_wasm_adapter::async_callback! { opendex_sc_sft_nft_staking }
