[package]
name = "opendex-sc-sft-nft-staking-controller-meta"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies.opendex-sc-sft-nft-staking-controller]
path = ".."

[dependencies.multiversx-sc-meta-lib]
version = "0.57.0"
default-features = false
