// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           26
// Async Callback:                       1
// Total number of exported functions:  28

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    opendex_sc_sft_nft_staking
    (
        init => init
        getStakingSftCollectionId => staking_sft_collection_id
        getRewardToken => reward_token
        getStakedNftCollectionId => staked_nft_collection_id
        getRewardPerSecond => reward_per_second
        getTotalStaked => total_staked
        getFeeReceiver => fee_receiver
        getPerformanceFeePercent => performance_fee_percent
        getRewardPeriodEnd => reward_end_time
        getRewardStartTime => reward_start_time
        getFunder => funder
        getLastUpdateTime => last_update_time
        getRewardPerTokenStored => reward_per_token_stored
        stake => stake
        unstake => unstake
        claimRewards => claim_rewards
        getPendingRewards => get_pending_rewards_view
        issueStakedNftCollection => issue_staked_nft_collection
        fundRewardsAndSetDuration => fund_rewards_and_set_duration
        setPerformanceFeePercent => set_performance_fee_percent_endpoint
        setFeeReceiver => set_fee_receiver
        setFunder => set_funder
        getCurrentRewardPerToken => current_reward_per_token
        isAdmin => is_admin
        addAdmin => add_admin
        removeAdmin => remove_admin
        getAdmins => admins
    )
}

multiversx_sc_wasm_adapter::async_callback! { opendex_sc_sft_nft_staking }
