name: CI

on:
  push:
    branches:
      - main
      - feature/*
  pull_request:

permissions:
  checks: write
  pull-requests: write

jobs:
  contracts:
    name: Contracts
    uses: javier-nft/mx-sc-actions/.github/workflows/contracts.yml@main
    with:
      rust-toolchain: stable
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
